name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        sudo apt-get install libasound2-dev /dev/null
        wget -q http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz
        tar xf pa_stable_v190700_20210406.tgz
        (cd portaudio; ./configure -q --disable-shared --without-jack --without-oss --without-asihpi)
        make -C portaudio >/dev/null
        cc -Wall -Wno-unused-result -O2 -s -Iportaudio/include yuleq.c portaudio/lib/.libs/libportaudio.a -pthread -lm -lasound -o yuleq
